//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/NotTahminApp")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdSoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DersSayisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GizliSoruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GizliSoruCevapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OturumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdSoyad {
            get {
                return this.AdSoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.AdSoyadField, value) != true)) {
                    this.AdSoyadField = value;
                    this.RaisePropertyChanged("AdSoyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DersSayisi {
            get {
                return this.DersSayisiField;
            }
            set {
                if ((this.DersSayisiField.Equals(value) != true)) {
                    this.DersSayisiField = value;
                    this.RaisePropertyChanged("DersSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GizliSoru {
            get {
                return this.GizliSoruField;
            }
            set {
                if ((object.ReferenceEquals(this.GizliSoruField, value) != true)) {
                    this.GizliSoruField = value;
                    this.RaisePropertyChanged("GizliSoru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GizliSoruCevap {
            get {
                return this.GizliSoruCevapField;
            }
            set {
                if ((object.ReferenceEquals(this.GizliSoruCevapField, value) != true)) {
                    this.GizliSoruCevapField = value;
                    this.RaisePropertyChanged("GizliSoruCevap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullaniciAdi {
            get {
                return this.KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciAdiField, value) != true)) {
                    this.KullaniciAdiField = value;
                    this.RaisePropertyChanged("KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Oturum {
            get {
                return this.OturumField;
            }
            set {
                if ((this.OturumField.Equals(value) != true)) {
                    this.OturumField = value;
                    this.RaisePropertyChanged("Oturum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentDTO", Namespace="http://schemas.datacontract.org/2004/07/NotTahminApp.Models")]
    [System.SerializableAttribute()]
    public partial class StudentDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdSoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DersSayisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GizliSoruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GizliSoruCevapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OturumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdSoyad {
            get {
                return this.AdSoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.AdSoyadField, value) != true)) {
                    this.AdSoyadField = value;
                    this.RaisePropertyChanged("AdSoyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DersSayisi {
            get {
                return this.DersSayisiField;
            }
            set {
                if ((this.DersSayisiField.Equals(value) != true)) {
                    this.DersSayisiField = value;
                    this.RaisePropertyChanged("DersSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GizliSoru {
            get {
                return this.GizliSoruField;
            }
            set {
                if ((object.ReferenceEquals(this.GizliSoruField, value) != true)) {
                    this.GizliSoruField = value;
                    this.RaisePropertyChanged("GizliSoru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GizliSoruCevap {
            get {
                return this.GizliSoruCevapField;
            }
            set {
                if ((object.ReferenceEquals(this.GizliSoruCevapField, value) != true)) {
                    this.GizliSoruCevapField = value;
                    this.RaisePropertyChanged("GizliSoruCevap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullaniciAdi {
            get {
                return this.KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciAdiField, value) != true)) {
                    this.KullaniciAdiField = value;
                    this.RaisePropertyChanged("KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Oturum {
            get {
                return this.OturumField;
            }
            set {
                if ((this.OturumField.Equals(value) != true)) {
                    this.OturumField = value;
                    this.RaisePropertyChanged("Oturum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lesson", Namespace="http://schemas.datacontract.org/2004/07/NotTahminApp")]
    [System.SerializableAttribute()]
    public partial class Lesson : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BütField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BütTahminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinalDurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FinalTahminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GecerNotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GecmeNotuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VizeDurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VizeTahminField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adi {
            get {
                return this.AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AdiField, value) != true)) {
                    this.AdiField = value;
                    this.RaisePropertyChanged("Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Büt {
            get {
                return this.BütField;
            }
            set {
                if ((this.BütField.Equals(value) != true)) {
                    this.BütField = value;
                    this.RaisePropertyChanged("Büt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BütTahmin {
            get {
                return this.BütTahminField;
            }
            set {
                if ((this.BütTahminField.Equals(value) != true)) {
                    this.BütTahminField = value;
                    this.RaisePropertyChanged("BütTahmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Final {
            get {
                return this.FinalField;
            }
            set {
                if ((this.FinalField.Equals(value) != true)) {
                    this.FinalField = value;
                    this.RaisePropertyChanged("Final");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FinalDurum {
            get {
                return this.FinalDurumField;
            }
            set {
                if ((object.ReferenceEquals(this.FinalDurumField, value) != true)) {
                    this.FinalDurumField = value;
                    this.RaisePropertyChanged("FinalDurum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinalTahmin {
            get {
                return this.FinalTahminField;
            }
            set {
                if ((this.FinalTahminField.Equals(value) != true)) {
                    this.FinalTahminField = value;
                    this.RaisePropertyChanged("FinalTahmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double GecerNot {
            get {
                return this.GecerNotField;
            }
            set {
                if ((this.GecerNotField.Equals(value) != true)) {
                    this.GecerNotField = value;
                    this.RaisePropertyChanged("GecerNot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GecmeNotu {
            get {
                return this.GecmeNotuField;
            }
            set {
                if ((this.GecmeNotuField.Equals(value) != true)) {
                    this.GecmeNotuField = value;
                    this.RaisePropertyChanged("GecmeNotu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vize {
            get {
                return this.VizeField;
            }
            set {
                if ((this.VizeField.Equals(value) != true)) {
                    this.VizeField = value;
                    this.RaisePropertyChanged("Vize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VizeDurum {
            get {
                return this.VizeDurumField;
            }
            set {
                if ((object.ReferenceEquals(this.VizeDurumField, value) != true)) {
                    this.VizeDurumField = value;
                    this.RaisePropertyChanged("VizeDurum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VizeTahmin {
            get {
                return this.VizeTahminField;
            }
            set {
                if ((this.VizeTahminField.Equals(value) != true)) {
                    this.VizeTahminField = value;
                    this.RaisePropertyChanged("VizeTahmin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LessonDTO", Namespace="http://schemas.datacontract.org/2004/07/NotTahminApp.Models")]
    [System.SerializableAttribute()]
    public partial class LessonDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdıField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BütField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BütTahminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinalDurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FinalTahminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GecerNotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GecmeNotuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VizeDurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VizeTahminField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adı {
            get {
                return this.AdıField;
            }
            set {
                if ((object.ReferenceEquals(this.AdıField, value) != true)) {
                    this.AdıField = value;
                    this.RaisePropertyChanged("Adı");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Büt {
            get {
                return this.BütField;
            }
            set {
                if ((this.BütField.Equals(value) != true)) {
                    this.BütField = value;
                    this.RaisePropertyChanged("Büt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BütTahmin {
            get {
                return this.BütTahminField;
            }
            set {
                if ((this.BütTahminField.Equals(value) != true)) {
                    this.BütTahminField = value;
                    this.RaisePropertyChanged("BütTahmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Final {
            get {
                return this.FinalField;
            }
            set {
                if ((this.FinalField.Equals(value) != true)) {
                    this.FinalField = value;
                    this.RaisePropertyChanged("Final");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FinalDurum {
            get {
                return this.FinalDurumField;
            }
            set {
                if ((object.ReferenceEquals(this.FinalDurumField, value) != true)) {
                    this.FinalDurumField = value;
                    this.RaisePropertyChanged("FinalDurum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinalTahmin {
            get {
                return this.FinalTahminField;
            }
            set {
                if ((this.FinalTahminField.Equals(value) != true)) {
                    this.FinalTahminField = value;
                    this.RaisePropertyChanged("FinalTahmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double GecerNot {
            get {
                return this.GecerNotField;
            }
            set {
                if ((this.GecerNotField.Equals(value) != true)) {
                    this.GecerNotField = value;
                    this.RaisePropertyChanged("GecerNot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GecmeNotu {
            get {
                return this.GecmeNotuField;
            }
            set {
                if ((this.GecmeNotuField.Equals(value) != true)) {
                    this.GecmeNotuField = value;
                    this.RaisePropertyChanged("GecmeNotu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vize {
            get {
                return this.VizeField;
            }
            set {
                if ((this.VizeField.Equals(value) != true)) {
                    this.VizeField = value;
                    this.RaisePropertyChanged("Vize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VizeDurum {
            get {
                return this.VizeDurumField;
            }
            set {
                if ((object.ReferenceEquals(this.VizeDurumField, value) != true)) {
                    this.VizeDurumField = value;
                    this.RaisePropertyChanged("VizeDurum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VizeTahmin {
            get {
                return this.VizeTahminField;
            }
            set {
                if ((this.VizeTahminField.Equals(value) != true)) {
                    this.VizeTahminField = value;
                    this.RaisePropertyChanged("VizeTahmin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SignUp", ReplyAction="http://tempuri.org/IService1/SignUpResponse")]
        void SignUp(Client.ServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SignUp", ReplyAction="http://tempuri.org/IService1/SignUpResponse")]
        System.Threading.Tasks.Task SignUpAsync(Client.ServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        Client.ServiceReference.StudentDTO Login(Client.ServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference.StudentDTO> LoginAsync(Client.ServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangePassword", ReplyAction="http://tempuri.org/IService1/ChangePasswordResponse")]
        bool ChangePassword(Client.ServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangePassword", ReplyAction="http://tempuri.org/IService1/ChangePasswordResponse")]
        System.Threading.Tasks.Task<bool> ChangePasswordAsync(Client.ServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TryChangePassword", ReplyAction="http://tempuri.org/IService1/TryChangePasswordResponse")]
        string TryChangePassword(Client.ServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TryChangePassword", ReplyAction="http://tempuri.org/IService1/TryChangePasswordResponse")]
        System.Threading.Tasks.Task<string> TryChangePasswordAsync(Client.ServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertLesson", ReplyAction="http://tempuri.org/IService1/InsertLessonResponse")]
        void InsertLesson(Client.ServiceReference.Lesson ls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertLesson", ReplyAction="http://tempuri.org/IService1/InsertLessonResponse")]
        System.Threading.Tasks.Task InsertLessonAsync(Client.ServiceReference.Lesson ls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllLesson", ReplyAction="http://tempuri.org/IService1/GetAllLessonResponse")]
        Client.ServiceReference.LessonDTO[] GetAllLesson(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllLesson", ReplyAction="http://tempuri.org/IService1/GetAllLessonResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference.LessonDTO[]> GetAllLessonAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateLesson", ReplyAction="http://tempuri.org/IService1/UpdateLessonResponse")]
        void UpdateLesson(Client.ServiceReference.Lesson ls, int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateLesson", ReplyAction="http://tempuri.org/IService1/UpdateLessonResponse")]
        System.Threading.Tasks.Task UpdateLessonAsync(Client.ServiceReference.Lesson ls, int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLesson", ReplyAction="http://tempuri.org/IService1/DeleteLessonResponse")]
        bool DeleteLesson(int Id, int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLesson", ReplyAction="http://tempuri.org/IService1/DeleteLessonResponse")]
        System.Threading.Tasks.Task<bool> DeleteLessonAsync(int Id, int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AccessControl", ReplyAction="http://tempuri.org/IService1/AccessControlResponse")]
        Client.ServiceReference.StudentDTO AccessControl(Client.ServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AccessControl", ReplyAction="http://tempuri.org/IService1/AccessControlResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference.StudentDTO> AccessControlAsync(Client.ServiceReference.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllStudents", ReplyAction="http://tempuri.org/IService1/GetAllStudentsResponse")]
        Client.ServiceReference.StudentDTO[] GetAllStudents(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllStudents", ReplyAction="http://tempuri.org/IService1/GetAllStudentsResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference.StudentDTO[]> GetAllStudentsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        void DeleteUser(int Id, int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(int Id, int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUser", ReplyAction="http://tempuri.org/IService1/UpdateUserResponse")]
        void UpdateUser(Client.ServiceReference.Student user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUser", ReplyAction="http://tempuri.org/IService1/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(Client.ServiceReference.Student user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.ServiceReference.IService1>, Client.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SignUp(Client.ServiceReference.Student s) {
            base.Channel.SignUp(s);
        }
        
        public System.Threading.Tasks.Task SignUpAsync(Client.ServiceReference.Student s) {
            return base.Channel.SignUpAsync(s);
        }
        
        public Client.ServiceReference.StudentDTO Login(Client.ServiceReference.Student s) {
            return base.Channel.Login(s);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference.StudentDTO> LoginAsync(Client.ServiceReference.Student s) {
            return base.Channel.LoginAsync(s);
        }
        
        public bool ChangePassword(Client.ServiceReference.Student s) {
            return base.Channel.ChangePassword(s);
        }
        
        public System.Threading.Tasks.Task<bool> ChangePasswordAsync(Client.ServiceReference.Student s) {
            return base.Channel.ChangePasswordAsync(s);
        }
        
        public string TryChangePassword(Client.ServiceReference.Student s) {
            return base.Channel.TryChangePassword(s);
        }
        
        public System.Threading.Tasks.Task<string> TryChangePasswordAsync(Client.ServiceReference.Student s) {
            return base.Channel.TryChangePasswordAsync(s);
        }
        
        public void InsertLesson(Client.ServiceReference.Lesson ls) {
            base.Channel.InsertLesson(ls);
        }
        
        public System.Threading.Tasks.Task InsertLessonAsync(Client.ServiceReference.Lesson ls) {
            return base.Channel.InsertLessonAsync(ls);
        }
        
        public Client.ServiceReference.LessonDTO[] GetAllLesson(int id) {
            return base.Channel.GetAllLesson(id);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference.LessonDTO[]> GetAllLessonAsync(int id) {
            return base.Channel.GetAllLessonAsync(id);
        }
        
        public void UpdateLesson(Client.ServiceReference.Lesson ls, int uid) {
            base.Channel.UpdateLesson(ls, uid);
        }
        
        public System.Threading.Tasks.Task UpdateLessonAsync(Client.ServiceReference.Lesson ls, int uid) {
            return base.Channel.UpdateLessonAsync(ls, uid);
        }
        
        public bool DeleteLesson(int Id, int uid) {
            return base.Channel.DeleteLesson(Id, uid);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteLessonAsync(int Id, int uid) {
            return base.Channel.DeleteLessonAsync(Id, uid);
        }
        
        public Client.ServiceReference.StudentDTO AccessControl(Client.ServiceReference.Student s) {
            return base.Channel.AccessControl(s);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference.StudentDTO> AccessControlAsync(Client.ServiceReference.Student s) {
            return base.Channel.AccessControlAsync(s);
        }
        
        public Client.ServiceReference.StudentDTO[] GetAllStudents(int id) {
            return base.Channel.GetAllStudents(id);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference.StudentDTO[]> GetAllStudentsAsync(int id) {
            return base.Channel.GetAllStudentsAsync(id);
        }
        
        public void DeleteUser(int Id, int uid) {
            base.Channel.DeleteUser(Id, uid);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(int Id, int uid) {
            return base.Channel.DeleteUserAsync(Id, uid);
        }
        
        public void UpdateUser(Client.ServiceReference.Student user) {
            base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(Client.ServiceReference.Student user) {
            return base.Channel.UpdateUserAsync(user);
        }
    }
}
